spring.application.name=AuraFit-Backend

# 1. Database Connection Details
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Database Table Management Rules
spring.jpa.hibernate.ddl-auto=update

# 3. Development Debugging Tools
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

port = 8081
