spring.application.name=AuraFit-Backend

# 1. Server Configuration
server.port=8080

# 2. Database Connection Details (Injected via IntelliJ)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}

# 3. PostgreSQL Translators
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Database Table Management Rules
spring.jpa.hibernate.ddl-auto=update

# 5. Development Debugging Tools
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG